name: Your New Jekyll Site
disqus_short_name: detailyang 
avatar: header.jpg
description: a very very easy person
paginate: 5
twitter: https://twitter.com/detailyang
github: https://github.com/detailyang
email: detailyang@gmail.com
markdown: redcarpet
pygments: true
about: <p>This guy is liberal and minimalist.he likes freedom and simpleness.he chases free and simplicity</p>
       <br/>
       <p>If you want to cantact this guy, please email him which is a best way</p>

       

